[package]
name = "hextuner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
crossterm = "0.28.1"
iced = { version = "0.13.1", features = ["lazy"] }
iced_aw = "0.12.0"
rfd = "0.15.2"
xdftuneparser = { version = "0.0.1", path = "../xdftuneparser" }
